name: AWS OIDC Test

on:
  push:
    branches:
      - corgi
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  test-aws:
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::009661764077:role/cicdRole
          aws-region: us-east-1

      - run: aws s3 ls s3://site781fe43f26b9eba3 --recursive
      - run: curl -s https://d67nf28gqfurd.cloudfront.net/ | head -100
      - run: aws s3 ls s3://codec4f26c862a321ef5 --recursive
      - run: aws s3 ls s3://platform-bucket-009661764077-us-east-1 --recursive
      - run: aws lambda get-function --function-name nslookupv2