name: AWS OIDC Test

on:
  push:
    branches:
      - corgi
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  test-aws:
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::009661764077:role/cicdRole
          aws-region: us-east-1

      - run: aws s3api list-buckets
      - run: aws lambda list-functions
      - run: aws ec2 describe-instances
      - run: aws ec2 describe-vpcs
      - run: aws cloudfront list-distributions